apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: sandbox
spec:
  ports:
    - port: 4111
      protocol: TCP
      targetPort: 3111
  selector:
    app: techtrends
    tag: latest
  type: ClusterIP
status:
  loadBalancer: {}
